# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
#
linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - one_member_abstracts
    - slash_for_doc_comments
    - sort_constructors_first
    - unnecessary_brace_in_string_interps
    - prefer_equal_for_default_values
    - prefer_generic_function_type_aliases
    - unawaited_futures
    - unnecessary_const
    - unnecessary_new


analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  enable-experiment:
    - non-nullable


# analyzer:
#  implicit-casts: false
#  implicit-dynamic: false
#   exclude:
#     - path/to/excluded/files/**
