name: pinenacl
description: The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
version: 0.1.3-dev.1
author: Pal Dorogi <pal.dorogi@gmail.com>
homepage: https://github.com/ilap/pinenacl-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fixnum: ^0.10.9
  convert: ^2.0.2
  bech32: ^0.1.2

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.0.0
