name: pinenacl
description: The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
version: 0.1.5
authors:
  - Pal Dorogi <pal.dorogi@gmail.com>
homepage: https://github.com/ilap/pinenacl-dart

environment:
  sdk: '>=2.7.0 <=2.10.4'

dependencies:
  fixnum: ^0.10.11
  convert: ^2.1.1
  bech32: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
