name: pinenacl
description: The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
version: 0.4.2
homepage: https://github.com/ilap/pinenacl-dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.17.4
  benchmark_harness: ^2.0.0
  lints: ^2.0.0
