name: pinenacl
description: The Dart implementation of the PyNaCl APIs with the TweetNaCl cryptographic library
version: 0.2.0-nullsafety.1
authors:
  - Pal Dorogi <pal.dorogi@gmail.com>
homepage: https://github.com/ilap/pinenacl-dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  fixnum: ^1.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety

