@startuml

title Digital Signature's class diagrams

class VerifyKey extends PublicKey implements Verify {

}

class SigningKey extends PrivateKey implements Sign {
  + static const seedSize = TweetNaCl.seedSize;
  + AsymmetricKey get publicKey => verifyKey;
  + final VerifyKey verifyKey;
}

@enduml
