name: Dart Test CI

on:
  push:
    branches:
      - master
      - releases/*
jobs:
  stable-channel:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Setup Dart VM
      uses: vanesyan/setup-dart@v1
      with:
        version: latest
        channel: stable
    - name: Install dependencies #1
      run: pub get
    - name: Run tests
      run: pub run test
