name: Dart

on:
  [push, pull_request]

jobs:

  # Default test configurations.
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: example
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]
        architecture: [x64, arm, arm64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print DART_HOME
        run: echo "Dart SDK installed in $DART_HOME"
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart run example/main.dart
      - run: dart run example/box.dart
      - run: dart run example/sealedbox.dart
      - run: dart run example/secretbox.dart
      - run: dart run example/secure.dart
      - run: dart run example/signature.dart
      - run: dart analyze
      - run: dart test


  # Default test configurations.
  test_32bit:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: example
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable]
        architecture: [ia32, arm]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print DART_HOME
        run: echo "Dart SDK installed in $DART_HOME"
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart run example/main.dart
      - run: dart run example/box.dart
      - run: dart run example/sealedbox.dart
      - run: dart run example/secretbox.dart
      - run: dart run example/secure.dart
      - run: dart run example/signature.dart
      - run: dart analyze
      - run: dart test
