name: Dart Test CI on ARMv7

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  armv7_test_action:
    runs-on: ubuntu-18.04
    name: Dart Test on ubuntu-18.04 armv7
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Test on armv7
        uses: uraimo/run-on-arch-action@v2.0.8
        with:
          arch: armv7
          distro: ubuntu18.04
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y git curl unzip coreutils file
            curl -L https://storage.googleapis.com/dart-archive/channels/beta/release/2.12.0-133.7.beta/sdk/dartsdk-linux-arm-release.zip -o /root/dartsdk-linux-arm-release.zip
          
          # GITHUB_WORKSPACE
          # /home/runner/work/setup-gleam/setup-gleam/
          # /github/workspace/
          run: |
            cd /root
            unzip -q dartsdk-linux-arm-release.zip
            cd /home/runner/work/pinenacl-dart/pinenacl-dart
            ls -l
            uname -a 
            file /root/dart-sdk/bin/pub
            /root/dart-sdk/bin/pub version
            /root/dart-sdk/bin/pub run test/tweetnacl_validation_test.dart
            /root/dart-sdk/bin/pub get 